test: ../../../src/sample/C/Example-C.cpp ../../../src/include/NLPIR.h
	 g++ ../../../src/sample/C/Example-C.cpp -L. -lpthread -L../../../lib/Linux64 -lNLPIR -Wall -Wunused -O3 -DOS_LINUX  -o example
