test: ../../../src/sample/c_seg/nlpir_seg_file.cpp ../../../src/include/NLPIR.h
	 g++ ../../../src/sample/c_seg/nlpir_seg_file.cpp -L. -lpthread -L../../../lib/Linux64 -lNLPIR -Wall -Wunused -O3 -DOS_LINUX  -o nlpir_seg_file
